
package com.rule.front;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ValidationImplService", targetNamespace = "http://front.rule.com/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class GetValidation
    extends Service
{

    private final static URL ValidationIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ValidationIMPLSERVICE_WSDL_LOCATION = url;
    }

    public GetValidation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetValidation() {
        super(ValidationIMPLSERVICE_WSDL_LOCATION, new QName("http://front.rule.com/", "ValidationImplService"));
    }

    /**
     * 
     * @return
     *     returns Validation
     */
    @WebEndpoint(name = "ValidationImplPort")
    public Validation getValidationImplPort() {
        return (Validation)super.getPort(new QName("http://front.rule.com/", "ValidationImplPort"), Validation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Validation
     */
    @WebEndpoint(name = "ValidationImplPort")
    public Validation getValidationImplPort(WebServiceFeature... features) {
        return (Validation)super.getPort(new QName("http://front.rule.com/", "ValidationImplPort"), Validation.class, features);
    }

}
